# Generated by Django 5.1.5 on 2025-04-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='permalink',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='post_id',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
